`timescale 1ns / 1ps

module de_stage (
    input  wire        clk,
    input  wire        reset,

    /*
        Inputs from Fetch/DE pipeline registers.
        These are already-latched Decode-stage values.
    */
    input  wire [15:0] de_npc,
    input  wire [15:0] de_ir,
    input  wire        de_v,

    /*
        MEM.STALL comes backward from MEM.
        If MEM is stalled, Decode/AGEX must not advance.
    */
    input  wire        mem_stall,

    /*
        Writeback inputs from SR stage to register file and CC register.
        These are also used by dependency_check for the SR stage.
    */
    input  wire [2:0]  sr_drid,
    input  wire [15:0] sr_reg_data,
    input  wire        v_sr_ld_reg,

    input  wire [2:0]  sr_cc_data,
    input  wire        v_sr_ld_cc,

    /*
        Inputs from AGEX and MEM for Dependency Check Logic.

        These tell Decode whether older instructions in AGEX/MEM
        are going to write a register or condition codes.
    */
    input  wire [2:0]  agex_drid_in,
    input  wire [2:0]  mem_drid,

    input  wire        v_agex_ld_reg,
    input  wire        v_mem_ld_reg,

    input  wire        v_agex_ld_cc,
    input  wire        v_mem_ld_cc,

    /*
        Decode-stage outputs to Fetch/control-stall logic.
    */
    output wire        ld_agex,
    output wire        agex_v_next,
    output wire        v_de_br_stall,
    output wire        dep_stall_debug,

    /*
        Outputs of DE/AGEX pipeline registers.
        These feed the AGEX stage.
    */
    output wire [15:0] agex_npc,
    output wire [15:0] agex_ir,
    output wire [15:0] agex_sr1,
    output wire [15:0] agex_sr2,
    output wire [2:0]  agex_cc,
    output wire [2:0]  agex_drid,
    output wire [20:0] agex_cs,
    output wire        agex_v,

    /*
        Optional debug outputs.
    */
    output wire [23:0] control_store_out_debug,

    output wire [2:0]  sr1_id_debug,
    output wire [2:0]  sr2_id_debug,
    output wire [2:0]  drid_debug,
    output wire [15:0] sr1_data_debug,
    output wire [15:0] sr2_data_debug,
    output wire [2:0]  cc_data_debug,

    output wire        sr1_needed_debug,
    output wire        sr2_needed_debug,
    output wire        de_br_op_debug,
    output wire        br_stall_debug,

    output wire [15:0] r0_debug,
    output wire [15:0] r1_debug,
    output wire [15:0] r2_debug,
    output wire [15:0] r3_debug,
    output wire [15:0] r4_debug,
    output wire [15:0] r5_debug,
    output wire [15:0] r6_debug,
    output wire [15:0] r7_debug
);

    /*
        24-bit control store output.

        New 24-bit layout after adding ALUK2:

            control_store_out[0]  = SR1.NEEDED
            control_store_out[1]  = SR2.NEEDED
            control_store_out[2]  = DRMUX

            control_store_out[3]  = ADDR1MUX
            control_store_out[4]  = ADDR2MUX1
            control_store_out[5]  = ADDR2MUX0
            control_store_out[6]  = LSHF1
            control_store_out[7]  = ADDRESSMUX
            control_store_out[8]  = SR2MUX
            control_store_out[9]  = ALUK2
            control_store_out[10] = ALUK1
            control_store_out[11] = ALUK0
            control_store_out[12] = ALU.RESULTMUX

            control_store_out[13] = BR.OP
            control_store_out[14] = UNCOND.OP
            control_store_out[15] = TRAP.OP
            control_store_out[16] = BR.STALL
            control_store_out[17] = DCACHE.EN
            control_store_out[18] = DCACHE.RW
            control_store_out[19] = DATA.SIZE

            control_store_out[20] = DR.VALUEMUX1
            control_store_out[21] = DR.VALUEMUX0
            control_store_out[22] = LD.REG
            control_store_out[23] = LD.CC

        Decode-only bits:
            [0] SR1.NEEDED
            [1] SR2.NEEDED
            [2] DRMUX

        AGEX.CS receives:
            [23:3], which is 21 bits.
    */
    wire [23:0] control_store_out;

    control_store CONTROL_STORE_UNIT (
        .de_ir(de_ir),
        .cs(control_store_out)
    );

    /*
        Control-store bit aliases.
    */
    wire sr1_needed;
    wire sr2_needed;
    wire drmux_sel;
    wire de_br_op;
    wire br_stall;

    assign sr1_needed = control_store_out[0];
    assign sr2_needed = control_store_out[1];
    assign drmux_sel  = control_store_out[2];

    /*
        These shifted because ALUK2 was inserted at bit [9].
    */
    assign de_br_op   = control_store_out[13];
    assign br_stall   = control_store_out[16];

    /*
        Register ID selection.

        SR1 is always DE.IR[8:6].

        SR2 goes through SR2.IDMUX:
            0 -> DE.IR[2:0]
            1 -> DE.IR[11:9]
    */
    wire [2:0] sr1_id;
    wire [2:0] sr2_id;
    wire [2:0] drid;

    assign sr1_id = de_ir[8:6];

/*
    SR2.IDMUX is generated by Decode-stage logic.

    0 -> DE.IR[2:0]
         Used by ADD/AND/XOR/MUL register-form instructions.

    1 -> DE.IR[11:9]
         Used by store instructions, where the value being stored is
         named in IR[11:9].

    STB opcode = 0011
    STW opcode = 0111

    Both have:
        DE.IR[15] = 0
        DE.IR[13] = 1
        DE.IR[12] = 1

    DE.IR[14] distinguishes STB from STW, but both need SR2.IDMUX = 1.
*/
wire not_de_ir_15;
wire sr2_idmux_sel;

not NOT_DE_IR_15(not_de_ir_15, de_ir[15]);

and SR2_IDMUX_SEL_LOGIC(
    sr2_idmux_sel,
    not_de_ir_15,
    de_ir[13],
    de_ir[12]
);

sr2_idmux SR2_IDMUX_UNIT (
    .de_ir_2_0(de_ir[2:0]),
    .de_ir_11_9(de_ir[11:9]),
    .sr2_idmux_sel(sr2_idmux_sel),
    .sr2_id(sr2_id)
);

    /*
        DRMUX:
            0 -> DE.IR[11:9]
            1 -> R7 / 3'b111
    */
    drmux DRMUX_UNIT (
        .de_ir_11_9(de_ir[11:9]),
        .drmux_sel(drmux_sel),
        .drid(drid)
    );

    /*
        Register file.

        Decode reads SR1/SR2.
        Store Result writes back through SR.DRID/SR.REG.DATA/V.SR.LD.REG.
    */
    wire [15:0] sr1_data;
    wire [15:0] sr2_data;

    regfile REGFILE_UNIT (
        .clk(clk),
        .reset(reset),

        .sr1_id(sr1_id),
        .sr2_id(sr2_id),

        .sr_drid(sr_drid),
        .sr_reg_data(sr_reg_data),
        .v_sr_ld_reg(v_sr_ld_reg),

        .sr1_data(sr1_data),
        .sr2_data(sr2_data),

        .r0_out(r0_debug),
        .r1_out(r1_debug),
        .r2_out(r2_debug),
        .r3_out(r3_debug),
        .r4_out(r4_debug),
        .r5_out(r5_debug),
        .r6_out(r6_debug),
        .r7_out(r7_debug)
    );

    /*
        Condition-code register.

        Decode reads current CC.
        Store Result writes new CC through SR.CC.DATA/V.SR.LD.CC.
    */
    wire [2:0] cc_data;

    cc_reg CC_REG_UNIT (
        .clk(clk),
        .reset(reset),

        .sr_cc_data(sr_cc_data),
        .v_sr_ld_cc(v_sr_ld_cc),

        .cc_out(cc_data)
    );

    /*
        Dependency Check Logic.

        DEP.STALL is asserted if Decode needs a source register
        that is still going to be written by an older instruction in
        AGEX, MEM, or SR.

        It also stalls a Decode-stage branch if an older instruction
        is going to update the condition codes.
    */
    wire dep_stall;

    dependency_check DEPENDENCY_CHECK_UNIT (
        .de_v(de_v),

        .de_sr1_id(sr1_id),
        .de_sr2_id(sr2_id),

        .sr1_needed(sr1_needed),
        .sr2_needed(sr2_needed),
        .de_br_op(de_br_op),

        .agex_drid(agex_drid_in),
        .mem_drid(mem_drid),
        .sr_drid(sr_drid),

        .v_agex_ld_reg(v_agex_ld_reg),
        .v_mem_ld_reg(v_mem_ld_reg),
        .v_sr_ld_reg(v_sr_ld_reg),

        .v_agex_ld_cc(v_agex_ld_cc),
        .v_mem_ld_cc(v_mem_ld_cc),
        .v_sr_ld_cc(v_sr_ld_cc),

        .dep_stall(dep_stall)
    );

    /*
        Decode control logic.

        Generates:
            LD.AGEX
            input to AGEX.V latch
            V.DE.BR.STALL
    */
    de_logic DE_LOGIC_UNIT (
        .de_v(de_v),
        .dep_stall(dep_stall),
        .mem_stall(mem_stall),
        .br_stall(br_stall),

        .ld_agex(ld_agex),
        .agex_v_next(agex_v_next),
        .v_de_br_stall(v_de_br_stall)
    );

    /*
        DE/AGEX pipeline latch bundle.

        This latches:
            AGEX.NPC
            AGEX.IR
            AGEX.SR1
            AGEX.SR2
            AGEX.CC
            AGEX.DRID
            AGEX.CS
            AGEX.V

        Since the control store is now 24 bits, AGEX.CS is:
            control_store_out[23:3]
        which is 21 bits.
    */
    de_agex_latches DE_AGEX_LATCHES_UNIT (
        .clk(clk),
        .reset(reset),
        .ld_agex(ld_agex),

        .de_npc(de_npc),
        .de_ir(de_ir),

        .sr1_data(sr1_data),
        .sr2_data(sr2_data),
        .cc_data(cc_data),

        .drid_in(drid),
        .control_store_out(control_store_out),
        .agex_v_next(agex_v_next),

        .agex_npc(agex_npc),
        .agex_ir(agex_ir),
        .agex_sr1(agex_sr1),
        .agex_sr2(agex_sr2),
        .agex_cc(agex_cc),
        .agex_drid(agex_drid),
        .agex_cs(agex_cs),
        .agex_v(agex_v)
    );

    /*
        Debug assignments.
    */
    assign control_store_out_debug = control_store_out;

    assign sr1_id_debug   = sr1_id;
    assign sr2_id_debug   = sr2_id;
    assign drid_debug     = drid;
    assign sr1_data_debug = sr1_data;
    assign sr2_data_debug = sr2_data;
    assign cc_data_debug  = cc_data;

    assign sr1_needed_debug = sr1_needed;
    assign sr2_needed_debug = sr2_needed;
    assign de_br_op_debug   = de_br_op;
    assign br_stall_debug   = br_stall;
    assign dep_stall_debug  = dep_stall;

endmodule